name: Test builds

on:
  push:
  pull_request:

jobs:

  other-test:
    name: Test build for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - '20.04'
        rust:
          - stable
    container:
      image: ghcr.io/whitty/gh_ubuntu_${{ matrix.os }}:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt update && env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential libssl-dev pkg-config

      - name: Reset toolchain
        run: |
          rm -f rust-toolchain.toml
        shell: bash

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy

      - name: Build
        run: cargo build

      - name: Unit-test
        run: cargo test

      - name: Analyze
        run: cargo clippy
